import {useEffect,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight} from 'lucide-react';
import {roomApi} from '../services/roomApi';
import {getParticipantId,getDisplayName} from '../utils/roomSession';
export default function JoinRoom({roomCode,onJoined}){const [params]=useSearchParams(),navigate=useNavigate();const [code,setCode]=useState(roomCode||''),[name,setName]=useState(getDisplayName),[info,setInfo]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const invite=params.get('invite')||undefined;
 useEffect(()=>{if(!roomCode)return;let active=true;roomApi.getInfo(roomCode,invite).then(data=>active&&setInfo(data.room||data)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[roomCode,invite]);
 async function join(e){e.preventDefault();setBusy(true);setError('');try{const result=await roomApi.joinRoom(code.toUpperCase(),{participantId:getParticipantId(),displayName:name.trim(),invite});if(onJoined)onJoined(result);else navigate(`/room/${result.room.room_code}`,{replace:true});}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="section"><div className="page-title"><span className="eyebrow">YOUR PEOPLE ARE WAITING</span><h1>There’s a place for you.</h1><p>Join the live photobooth with a room code and your name.</p></div><form className="join-room-form" onSubmit={join}><label>Room code<input required pattern="[A-Za-z0-9]{6}" maxLength={6} autoCapitalize="characters" autoComplete="off" className="room-code-input" placeholder="X7K2PA" value={code} onChange={e=>{setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''));setError('');}} disabled={!!roomCode||busy}/></label><label>Your display name<input required maxLength={40} autoComplete="nickname" placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label>{info&&<p className="help-text">Up to {info.max_participants} friends · {info.photo_count} photos each</p>}{error&&<p className="room-error" role="alert">{error}</p>}<button className="button full" disabled={busy||code.length!==6||!name.trim()}>{busy?<><span className="spinner"/>Finding your people...</>:<>Join room <ArrowRight size={18}/></>}</button><p className="help-text">We’ll ask for camera access when you enter. Your microphone stays off.</p><Link to="/together/create" className="text-link">Or create your own room →</Link></form></main>;
}
